package collections.mapeamento;
// Generated 06/07/2014 13:30:02 by Hibernate Tools 3.2.1.GA

/**
 * TbAnaliseMedicamento generated by hbm2java
 */

public class TbAnaliseMedicamento  implements java.io.Serializable {


     private Integer idAnaliseMedicamento;
     private TbColaborador tbColaborador;
     private TbMedicamento tbMedicamento;
     private String relatorioAnaliseMedicamento;
     private String tipoAnaliseMedicamento;
     private String desAnaliseMedicamento;

    public TbAnaliseMedicamento() {
    }

	
    public TbAnaliseMedicamento(TbColaborador tbColaborador, TbMedicamento tbMedicamento, String desAnaliseMedicamento) {
        this.tbColaborador = tbColaborador;
        this.tbMedicamento = tbMedicamento;
        this.desAnaliseMedicamento = desAnaliseMedicamento;
    }
    public TbAnaliseMedicamento(TbColaborador tbColaborador, TbMedicamento tbMedicamento, String relatorioAnaliseMedicamento, String tipoAnaliseMedicamento, String desAnaliseMedicamento) {
       this.tbColaborador = tbColaborador;
       this.tbMedicamento = tbMedicamento;
       this.relatorioAnaliseMedicamento = relatorioAnaliseMedicamento;
       this.tipoAnaliseMedicamento = tipoAnaliseMedicamento;
       this.desAnaliseMedicamento = desAnaliseMedicamento;
    }
   
   
    public Integer getIdAnaliseMedicamento() {
        return this.idAnaliseMedicamento;
    }
    
    public void setIdAnaliseMedicamento(Integer idAnaliseMedicamento) {
        this.idAnaliseMedicamento = idAnaliseMedicamento;
    }

    public TbColaborador getTbColaborador() {
        return this.tbColaborador;
    }
    
    public void setTbColaborador(TbColaborador tbColaborador) {
        this.tbColaborador = tbColaborador;
    }

    public TbMedicamento getTbMedicamento() {
        return this.tbMedicamento;
    }
    
    public void setTbMedicamento(TbMedicamento tbMedicamento) {
        this.tbMedicamento = tbMedicamento;
    }
    
 
    public String getRelatorioAnaliseMedicamento() {
        return this.relatorioAnaliseMedicamento;
    }
    
    public void setRelatorioAnaliseMedicamento(String relatorioAnaliseMedicamento) {
        this.relatorioAnaliseMedicamento = relatorioAnaliseMedicamento;
    }

    public String getTipoAnaliseMedicamento() {
        return this.tipoAnaliseMedicamento;
    }
    
    public void setTipoAnaliseMedicamento(String tipoAnaliseMedicamento) {
        this.tipoAnaliseMedicamento = tipoAnaliseMedicamento;
    }
    
  
    public String getDesAnaliseMedicamento() {
        return this.desAnaliseMedicamento;
    }
    
    public void setDesAnaliseMedicamento(String desAnaliseMedicamento) {
        this.desAnaliseMedicamento = desAnaliseMedicamento;
    }




}


