package collections.mapeamento;
// Generated 06/07/2014 13:30:02 by Hibernate Tools 3.2.1.GA




/**
 * TbComposicao generated by hbm2java
 */

public class TbComposicao   {


     private Integer idtComposicao;
     private TdEmpresa tdEmpresa;
    

    public TbComposicao() {
    }

	
    public TbComposicao(TdEmpresa tdEmpresa) {
        this.tdEmpresa = tdEmpresa;
    }
  
   
 
    public Integer getIdtComposicao() {
        return this.idtComposicao;
    }
    
    public void setIdtComposicao(Integer idtComposicao) {
        this.idtComposicao = idtComposicao;
    }

    public TdEmpresa getTdEmpresa() {
        return this.tdEmpresa;
    }
    
    public void setTdEmpresa(TdEmpresa tdEmpresa) {
        this.tdEmpresa = tdEmpresa;
    }

    
    
   
    




}


