package collections.mapeamento;
// Generated 06/07/2014 13:30:02 by Hibernate Tools 3.2.1.GA




/**
 * TbUnidadeMedida generated by hbm2java
 */

public class TbUnidadeMedida   {


     
     private String sglUnidadeMedida;
    

    public TbUnidadeMedida() {
    }

	
    public TbUnidadeMedida(String sglUnidadeMedida) {
        this.sglUnidadeMedida = sglUnidadeMedida;
    }
   
   
  
   
    
    
    public String getSglUnidadeMedida() {
        return this.sglUnidadeMedida;
    }
    
    public void setSglUnidadeMedida(String sglUnidadeMedida) {
        this.sglUnidadeMedida = sglUnidadeMedida;
    }





}


