package collections.mapeamento;
// Generated 06/07/2014 13:30:02 by Hibernate Tools 3.2.1.GA



/**
 * TdViaAdministracao generated by hbm2java
 */

public class TdViaAdministracao  implements java.io.Serializable {


     private Integer idtViaAdministracao;
     private String dscViaAdministracao;


    public TdViaAdministracao() {
    }

	
    public TdViaAdministracao(String dscViaAdministracao) {
        this.dscViaAdministracao = dscViaAdministracao;
    }
   
   
   
    public Integer getIdtViaAdministracao() {
        return this.idtViaAdministracao;
    }
    
    public void setIdtViaAdministracao(Integer idtViaAdministracao) {
        this.idtViaAdministracao = idtViaAdministracao;
    }
    
  
    public String getDscViaAdministracao() {
        return this.dscViaAdministracao;
    }
    
    public void setDscViaAdministracao(String dscViaAdministracao) {
        this.dscViaAdministracao = dscViaAdministracao;
    }

   




}


