package seguranca.model;
// Generated 30/09/2013 13:52:59 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbSistema generated by hbm2java
 */
@Entity
@Table(name="tb_sistema"
    ,catalog="bd_prototipo"
)
public class TbSistema  implements java.io.Serializable {


     private Integer idtSistema;
     private String usrSistemaCad;
     private Date dtaSistemaCad;
     private String usrSistemaMod;
     private Date dtaSistemaMod;
     private String sglSistema;
     private String nmeSistema;
     private String vrsSistema;
     private String dscSistema;
     private Set<TbMenu> tbMenus = new HashSet<TbMenu>(0);

    public TbSistema() {
    }

	
    public TbSistema(String usrSistemaCad, Date dtaSistemaCad, String sglSistema, String nmeSistema, String vrsSistema) {
        this.usrSistemaCad = usrSistemaCad;
        this.dtaSistemaCad = dtaSistemaCad;
        this.sglSistema = sglSistema;
        this.nmeSistema = nmeSistema;
        this.vrsSistema = vrsSistema;
    }
    public TbSistema(String usrSistemaCad, Date dtaSistemaCad, String usrSistemaMod, Date dtaSistemaMod, String sglSistema, String nmeSistema, String vrsSistema, String dscSistema, Set<TbMenu> tbMenus) {
       this.usrSistemaCad = usrSistemaCad;
       this.dtaSistemaCad = dtaSistemaCad;
       this.usrSistemaMod = usrSistemaMod;
       this.dtaSistemaMod = dtaSistemaMod;
       this.sglSistema = sglSistema;
       this.nmeSistema = nmeSistema;
       this.vrsSistema = vrsSistema;
       this.dscSistema = dscSistema;
       this.tbMenus = tbMenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idt_sistema", unique=true, nullable=false)
    public Integer getIdtSistema() {
        return this.idtSistema;
    }
    
    public void setIdtSistema(Integer idtSistema) {
        this.idtSistema = idtSistema;
    }
    
    @Column(name="usr_sistema_cad", nullable=false, length=20)
    public String getUsrSistemaCad() {
        return this.usrSistemaCad;
    }
    
    public void setUsrSistemaCad(String usrSistemaCad) {
        this.usrSistemaCad = usrSistemaCad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_sistema_cad", nullable=false, length=10)
    public Date getDtaSistemaCad() {
        return this.dtaSistemaCad;
    }
    
    public void setDtaSistemaCad(Date dtaSistemaCad) {
        this.dtaSistemaCad = dtaSistemaCad;
    }
    
    @Column(name="usr_sistema_mod", length=20)
    public String getUsrSistemaMod() {
        return this.usrSistemaMod;
    }
    
    public void setUsrSistemaMod(String usrSistemaMod) {
        this.usrSistemaMod = usrSistemaMod;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dta_sistema_mod", length=10)
    public Date getDtaSistemaMod() {
        return this.dtaSistemaMod;
    }
    
    public void setDtaSistemaMod(Date dtaSistemaMod) {
        this.dtaSistemaMod = dtaSistemaMod;
    }
    
    @Column(name="sgl_sistema", nullable=false, length=30)
    public String getSglSistema() {
        return this.sglSistema;
    }
    
    public void setSglSistema(String sglSistema) {
        this.sglSistema = sglSistema;
    }
    
    @Column(name="nme_sistema", nullable=false, length=80)
    public String getNmeSistema() {
        return this.nmeSistema;
    }
    
    public void setNmeSistema(String nmeSistema) {
        this.nmeSistema = nmeSistema;
    }
    
    @Column(name="vrs_sistema", nullable=false, length=10)
    public String getVrsSistema() {
        return this.vrsSistema;
    }
    
    public void setVrsSistema(String vrsSistema) {
        this.vrsSistema = vrsSistema;
    }
    
    @Column(name="dsc_sistema", length=65535)
    public String getDscSistema() {
        return this.dscSistema;
    }
    
    public void setDscSistema(String dscSistema) {
        this.dscSistema = dscSistema;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbSistema")
    public Set<TbMenu> getTbMenus() {
        return this.tbMenus;
    }
    
    public void setTbMenus(Set<TbMenu> tbMenus) {
        this.tbMenus = tbMenus;
    }




}


